# background_opacity 0.75

confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Gilded
include gilded.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="Adwaita Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
